modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20No%20Hostiles%20Around%20Campfire"
logoFile="icon.png"

[[mods]]
modId="nohostilesaroundcampfire"
version="5.4"
displayName="No Hostiles Around Campfire"
displayURL="https://curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire"
authors="Rick South"
description='''Prevent hostile mobs from spawning around the campfire and burn existing mobs when placing a campfire down. With a configurable radius.
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, nbtc971, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.nohostilesaroundcampfire]]
    modId="collective"
    mandatory=true
    versionRange="[6.52,)"
    ordering="NONE"
    side="BOTH"